require:
  - rubocop-rails

inherit_from:
 - ./private/rspec.yml
 - ./private/standard.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRailsVersion: 5.2

Style/AsciiComments:
 Enabled: false

Style/ClassAndModuleChildren:
 Enabled: false

Style/Documentation:
 Enabled: false

Style/NumericPredicate:
 EnforcedStyle: comparison